alias ls="lsd --group-directories-first"
alias la="lsd -lah --group-directories-first"
alias python="python3"
# alias wget="wget --hsts-file=~/.dotfiles/.wget-hsts"
alias xclip="xclip -sel c"
alias act="conda activate"
alias deact="conda deactivate"
alias dc="docker-compose"
alias suggest="gh copilot suggest"
alias explain="gh copilot explain"
alias cat="bat"
alias fnlock="echo 0 | sudo tee /sys/module/hid_apple/parameters/fnmode"
alias vim="nvim"
alias open="xdg-open"
alias wezterm="flatpak run org.wezfurlong.wezterm"
alias killssh="ps aux | grep sshfs | head -n 1 | awk '{print \$2}' | xargs kill -9"
alias rename="wezterm cli rename-workspace"
